apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-torch-serving-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-torch-serving-pod
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50 # CPU 사용률이 50%를 유지하도록 스케일링
  minReplicas: 1  # 최소 Replica 수
  maxReplicas: 10 # 최대 Replica 수