apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-pod
spec:
  replicas: 3  # 현재 실행 중인 Pod의 개수를 3으로 변경
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      containers:
      - name: my-fastapi-container
        image: dyddkdlel33/my-fastapi-app
        ports:
          - containerPort: 30000 # FastAPI 애플리케이션이 사용하는 포트

---
apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
  labels:
    app: my-fastapi-app
spec:
  selector:
    app: my-fastapi-app
  ports:
    - name: http
      port: 30000
      targetPort: 30000
  type: LoadBalancer