apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
  labels:
    app: my-fastapi-app
spec:
  selector:
    app: my-fastapi-app
  ports:
    - name: http
      port: 30000
      targetPort: 30000
  type: LoadBalancer