apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: fastapi-service
            subset: v01-group
          weight: 80
        - destination:
            host: fastapi-service
            subset: v02-group
          weight: 20
    - match:
        - uri:
            exact: /predictions/densenet161
      route:
        - destination:
            host: torch-serving-service
    - match:
        - uri:
            exact: /v1/models/test_model:predict
      route:
        - destination:
            host: tf-serving-service
---
kind: DestinationRule       # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-our-canary-release # This can be anything you like.
  namespace: default
spec:
  host: fastapi-service # Service
  subsets:
    - labels:   # SELECTOR.
        version: v01 # find pods with label "safe"
      name: v01-group
    - labels:
        version: v02
      name: v02-group