apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
    - fastapi-service.default.svc.cluster.local
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: fastapi-service.default.svc.cluster.local
            subset: v01-group
          weight: 80
        - destination:
            host: fastapi-service.default.svc.cluster.local
            subset: v02-group
          weight: 20
---
kind: DestinationRule       # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-our-canary-release # This can be anything you like.
  namespace: default
spec:
  host: fastapi-service # Service
  subsets:
    - labels:   # SELECTOR.
        version: v01 # find pods with label "safe"
      name: v01-group
    - labels:
        version: v02
      name: v02-group