apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-torch-serving-pod
spec:
  replicas: 1  # 현재 실행 중인 Pod의 개수를 3으로 변경
  selector:
    matchLabels:
      app: my-torch-serving-app
  template:
    metadata:
      labels:
        app: my-torch-serving-app
    spec:
      containers:
      - name: my-torch-serving-container
        image: dyddkdlel33/my-torch-serving-app
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "4G"         # 메모리 최소: 4GB
            cpu: "4"             # CPU(Core) 개수 최소: 4개
          limits:
            memory: "8G"         # 메모리 최대: 8GB
            cpu: "8"             # CPU(Core) 개수 최소: 8개
            nvidia.com/gpu: "1"  # GPU 개수 최대: 1개
---
apiVersion: v1
kind: Service
metadata:
  name: torch-serving-service
  labels:
    app: my-torch-serving-app
spec:
  selector:
    app: my-torch-serving-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080