kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: circuit-breaker-for-the-entire-default-namespace
  namespace: default
spec:
  host: fastapi-service # Service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection: # Circuit Breakers HAVE TO BE SWITCHED ON
      maxEjectionPercent: 100
      consecutiveErrors: 2
      interval: 1s
      baseEjectionTime: 30s